Social media website - Milestone: friendships v1
Emmyn5600/Stay-in-touch pull request #1
Opened 2021-05-11 15:56 UTC by Emmyn5600

## On this pull request I implemented the following features:

* ### Created a model with associations and all requested features for friendships.
* ### I styled the Add friendship button 
* ### Make User account visible at the top of Navbar with his or her information.

2021-05-11 18:44 UTC, mricanho commented on config/database.yml
Change this file to work only with default, without username and password

2021-05-11 18:49 UTC, mricanho requested changes
# 🔴  Changes Required 🔴  

Hello @Emmyn5600, you did a good job on this milestone🔥, just a few changes are required:

- [x]  **You need to change the .ruby-version file from 2.7.0 to 2.7.2** 
- [ ] **Change the database.yml to work with default without user and password**
- [x] **The button Add Friend must disappear or change in any way once you click on it, because, you know, you only Add a Friend once until the other person accept or reject the friendship**
- [x] **You don't need a button to Add Friend if it's your own profile, right now you have the button active for your own profile**
- [x] **When a friendship is to send, the person who receives it needs a notification about it**
- [x] **Your Add Friend action controller, right now have a routing problem that prevents that something happens once you click it, please fix it**
- [ ] **User can reject a friendship request, please add this perk**
- [ ] **Add unit tests for your methods and integration tests**

I know it's a lot, but got this!

![tuesday](https://user-images.githubusercontent.com/60631456/117868807-a5e7c800-b25f-11eb-8714-6fae0468bdec.gif)


You can contact me on slack if you have any questions just search for me as @ Miguel Ricaño.

### 💻 👩🏽‍💻  Happy Coding!👨🏽‍💻  🖥️

2021-05-11 22:34 UTC, enaburekhan requested changes
# Status: Changes required:wrench::hammer::full_moon:
**Hi Emmy!
Great job so far:clap::clap:. However, we just need to make a few changes to get the project approved:muscle:.**

**To improve**

- [ ] I get this [error](https://imgur.com/a/JUbyqeb) when I run `bundle exec rspec`. Check if the path for the `require_relative` is the correct path for both the implemented `friendship` and `user` model. And kindly add more tests. Both unit and integration test.

**Optional**

- [ ] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Currently, it includes every registered users in the app. Instead of the current logged-in `user` and his/her `friends`. It will be nice to fix this.

Make the above-required changes and when you are ready, request another review.

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

2021-05-12 10:45 UTC, descholar-ceo requested changes
Hello @Emmyn5600 , kindly fix the mentioned issues, for me the rspec is still failing with the following error on screenshot
![Screenshot from 2021-05-12 12-45-09](https://user-images.githubusercontent.com/56886064/117962818-eeff5100-b31f-11eb-959e-9b81612a864e.png)

2021-05-12 10:50 UTC, Emmyn5600 commented
You can check, now it is working fine.

On Wed, May 12, 2021 at 12:46 PM Mugirase Emmanuel ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hello @Emmyn5600 <https://github.com/Emmyn5600> , kindly fix the
> mentioned issues, for me the rspec is still failing with the following
> error on screenshot
> [image: Screenshot from 2021-05-12 12-45-09]
> <https://user-images.githubusercontent.com/56886064/117962818-eeff5100-b31f-11eb-959e-9b81612a864e.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Emmyn5600/ror-social-scaffold/pull/1#pullrequestreview-657735073>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANIPACIEVLSXYJV6WTMO2J3TNJL7BANCNFSM44V6WW7Q>
> .
>

2021-05-12 11:50 UTC, ElijahTobs approved these changes
# Status: Approved! :tada: 

## Congratulations @Emmyn5600  

### Good job implementing the change as requested by the previous TSE.

## OPTIONAL 
* [ ] Your posts timeline should include posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Currently, it includes posts from other users who are not friends.


## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

2021-05-12 11:57 UTC, merged